In [158]:
#array numpy
import numpy as np
a =  np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[0])

[1 2 3 4]


In [168]:
#mwmbuat vector tanpa numpy
def pythonsum(n):
    a = b = list(range(n)) 
    c = []
    for i in range(len(a)):
        x = a[i] ** 2 
        y = b[i] ** 3 
        c.append(x + y )
    return c 

c = pythonsum(10)    
print(c)

[0, 2, 12, 36, 80, 150, 252, 392, 576, 810]


In [169]:
#dengan menggunakan numpy
def numpysum(n):
    a = np.arange(n) ** 2 
    b = np.arange(n) ** 3 
    c=a + b 
    return c

In [164]:
x = numpysum(10)
print(x)

[  0   2  12  36  80 150 252 392 576 810]


In [170]:
from datetime import datetime
size = 100
start = datetime.now()
c = pythonsum(size)
delta = datetime.now() - start
print("The last 2 elements of the sum", c[-2:])
print("PythonSum elapsed time in microseconds", delta.microseconds)

The last 2 elements of the sum [950796, 980100]
PythonSum elapsed time in microseconds 727


In [166]:
start = datetime.now()
c = numpysum(size)
delta = datetime.now() - start
print("The last 2 elements of the sum", c[-2:])
print("NumPySum elapsed time in microseconds", delta.microseconds)

The last 2 elements of the sum [950796 980100]
NumPySum elapsed time in microseconds 0


In [171]:
import numpy

In [172]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

Membuat ndarray

In [173]:
import numpy as np

In [174]:
my_list = list(range(5))
my_list
print(type(my_list))

<class 'list'>


In [175]:
array_1 = np.array(my_list)
print(type(array_1))
array_1

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4])

In [176]:
print("array1 :\n", array_1)

array1 :
 [0 1 2 3 4]


In [177]:
#membuat array dengan range element
print(np.arange(4)) #mulai dari 0 sampai 4, tetapi 4 tidak disertakan, dan angka ditambah 1
print(np.arange(2,15)) #mulai dari 2 sampai 15, tetapi 15 tidak disertakan dan angka ditambah 1
print(np.arange(1,15,2)) #mulai dari 1 sampai 15, tetapi 15 jangan diikuti dan angka ditambah 2

[0 1 2 3]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1  3  5  7  9 11 13]


In [178]:
arr = np.array([2, 3, 4, 5])
print(arr)

[2 3 4 5]


In [179]:
#menambahkan elemn ke array dengan np.append()
arr = np.append(arr, [6, 7])
print(arr)

[2 3 4 5 6 7]


In [180]:
#menghapus index 2 (perhitungan dimulai dari 0)
np.delete(arr, 2)

array([2, 3, 5, 6, 7])

In [181]:
arrsort = np.array([5, 7, 9, 8, 6, 3, 4])

In [182]:
#mengurutkan elemen dengan np.sort()
data = np.sort(arrsort)
print(data)

[3 4 5 6 7 8 9]


In [183]:
#array 1 dimensi
arr_1 = np.array([4, 6, 3, 8, 1, 7])
print(arr_1)

[4 6 3 8 1 7]


In [184]:
#untuk tahu jumlah dimensi yang digunakan dengan .ndim
arr_1.ndim

1

In [185]:
#untuk mengetahui jumlah elemen yang dimiliki dari masing-masing dimensi
arr_1.shape

(6,)

In [186]:
#untuk mengetahui jumlah elemen pada array
arr_1.size

6

In [187]:
#array 2 dimensi
import numpy as np
multi_list = [[0, 1, 2, 3], [10, 11, 12, 13]]
print(type(multi_list))
multi_list

<class 'list'>


[[0, 1, 2, 3], [10, 11, 12, 13]]

In [189]:
a = np.array(multi_list)
print(type(a)) #untuk mengetahui tipe dari a
print(a.ndim) #untuk mengetahui jumlah dimensi yang digunakan
a.shape #yang mengartikan bahwa dimensi 1 memiliki 2 elemen dan dimensi kedua memliki 4 elemen

<class 'numpy.ndarray'>
2


(2, 4)

In [190]:
#array 3 dimensi
array_3 = np.array([[[2, 4, 6, 7],
                     [6, 8, 9, 7]],
                    
                    [[2, 4, 6, 7],
                     [6, 8, 9, 7]],
                     
                    [[2, 4, 6, 7],
                     [6, 8, 9, 7]]])
                
print(array_3)

[[[2 4 6 7]
  [6 8 9 7]]

 [[2 4 6 7]
  [6 8 9 7]]

 [[2 4 6 7]
  [6 8 9 7]]]


In [191]:
print(a)

[[ 0  1  2  3]
 [10 11 12 13]]


In [192]:
#contoh jika ingin mengakses suatu elemen dengan indeks
a[1,2]

12

In [193]:
#sorting array dengan .sort
x = np.array([[3, 6, 8, 5],[1, 4, 7, 0]])
np.sort(x)

array([[3, 5, 6, 8],
       [0, 1, 4, 7]])

In [194]:
#axis = 0 yang dimana elemen diurutkan dari yg kecil sesuai kolom
x.sort(axis=0)
print(x)

[[1 4 7 0]
 [3 6 8 5]]


In [195]:
#axis = 1 yang dimana elemen diurutkan dari yag kecil sesuai baris
x.sort(axis=1)
print(x)

[[0 1 4 7]
 [3 5 6 8]]


In [196]:
#saat kita ingin numpy menginisialisa nilai array buat kita, yang dimana kita hanya perlu memberikan jumlah elemen yang kita mau
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [197]:
dzero = np.zeros((3, 3, 3))
print(dzero)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [198]:
dzero.shape

(3, 3, 3)

In [ ]:
ones_array = np.ones(8)
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
empty_array = np.empty((4, 3, 2))
empty_array

array([[[1.35478091e-311, 7.31217156e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.42413554e-306, 1.16095484e-028]],

       [[9.13599533e+242, 3.65299313e+233],
        [3.65881463e+233, 1.91073488e+137],
        [1.05747862e+214, 1.20338003e+132]],

       [[8.48585409e-096, 1.49888993e-076],
        [6.35226565e-067, 4.10123869e+223],
        [1.11666793e+277, 9.77081644e+199]],

       [[9.14433370e+135, 1.05747862e+214],
        [1.46899930e+179, 9.08367237e+223],
        [1.16466228e-028, 2.66287295e-312]]])

In [199]:
#jika ingin mengubah bentuk array tanpa perlu merubah datanya yaitu dengan np.reshape
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [200]:
b = a.reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]


In [201]:
#jika ingin meningkatkan dimensi array yang kita punya
variabelA = np.array([1, 2, 3, 4, 5, 6])
variabelA.shape

(6,)

In [202]:
a2 = variabelA[np.newaxis]
print(a2.shape)
print(a2)
a2.ndim 

(1, 6)
[[1 2 3 4 5 6]]


2

In [203]:
row_vector = variabelA[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [206]:
#mengubahnya menjadi 2 dimensi
col_vector = a2[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(1, 1, 6)
[[[1 2 3 4 5 6]]]


In [209]:
#cara memperluas array dengan menyisipkan axis baru dengan np.expand_dims
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [210]:
b = np.expand_dims(a, axis=1)
b.shape
print(b.shape)
print(b)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [45]:
c = np.expand_dims(c, axis=0)
print(c.shape)
print(c)

(1, 6)
[[1 2 3 4 5 6]]


In [46]:
#kita dapat mengindeks array numpy dengan cara yang sama seperti biasa
data = np.array([1, 2, 3])
print(data)

[1 2 3]


In [47]:
print(data[0:2])

[1 2]


In [48]:
print(data[-2:]) 

[2 3]


In [50]:
#kita dapat melakukan slice pada array numpy dengan (arr[:])
arr = np.array([3, 4, 5, 6,7])
print(arr[1:])

[4 5 6 7]


In [58]:
print(repr(arr[1:3]))

array([4, 5])


In [61]:
print(repr(arr[-3:]))

array([5, 6, 7])


In [62]:
#kita dapat memilih nilai array yang kita tentukan sesuai kondisi langsung dengan numpy
a = np.array([[4, 5, 6],[7, 8, 9], [10, 11, 12]])
print(a)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [63]:
print(a[a<9]) #mencetak nilai yang ada di dalam array kurang dari 9

[4 5 6 7 8]


In [65]:
number = a[a%3==0] #mencetak nilai yang ada di dalam array yang habis di bagi 3
print(number)

[ 6  9 12]


In [68]:
#kita dapat mengiris array seperti diatas, hanya dengan menentukan nilai yang kita mau
arr = np.array([5, 6, 7, 8, 9, 10, 11, 12, 13])
arr1 = arr[2:7]
arr1

array([ 7,  8,  9, 10, 11])

In [69]:
#kita dapat menumpuk array dengan vstack (veritikal) dan hstack(horizontal)
a_1 = np.array([[2, 3],
                [6, 7]])

In [71]:
a_2 = np.array([[8, 9],
                [4, 5]])

In [73]:
np.vstack((a_1, a_2))

array([[2, 3],
       [6, 7],
       [8, 9],
       [4, 5]])

In [74]:
np.hstack((a_1, a_2))

array([[2, 3, 8, 9],
       [6, 7, 4, 5]])

In [82]:
#jika kita memiliki array yang panjang, lalu kita ingin membagi nya menjadi beberapa bagian maka kita dapat menggunkan hsplit
arrsplit = np.array([[1, 3, 5, 7, 9, 11, 13, 15, 17, 17, 17, 17],
                      [19, 21, 23, 25, 27, 29, 31, 33, 35, 35, 35, 35]])
print(arrsplit)

[[ 1  3  5  7  9 11 13 15 17 17 17 17]
 [19 21 23 25 27 29 31 33 35 35 35 35]]


In [86]:
np.hsplit(arrsplit, 4)

[array([[ 1,  3,  5],
        [19, 21, 23]]),
 array([[ 7,  9, 11],
        [25, 27, 29]]),
 array([[13, 15, 17],
        [31, 33, 35]]),
 array([[17, 17, 17],
        [35, 35, 35]])]

In [87]:
#membuat objek array baru yang dimana dapat mencetak data yang sama
b = arrsplit.view()

In [88]:
print(b)

[[ 1  3  5  7  9 11 13 15 17 17 17 17]
 [19 21 23 25 27 29 31 33 35 35 35 35]]


In [89]:
#membuat salinan array baru dengan data yang sama
c = arrsplit.copy()

In [90]:
print(c)

[[ 1  3  5  7  9 11 13 15 17 17 17 17]
 [19 21 23 25 27 29 31 33 35 35 35 35]]


In [95]:
#jika kita ingin mengubah isi nilai array, tetapi tidak ingin nilai aslinya itu ikut berubah maka dapat menggunkan fungsi copy()
#contoh jika tidak menggunakan fungsi copy(), maka nilai dari var p akan ikut berubah 
p = [1, 3]
q = [5, 7]
r = p

print(p)
r[1] = 0
print(p) #ikut berubah


[1, 3]
[1, 0]


In [96]:
#menggunakan copy(), maka nilai dari variabel asli tidak akan ikut berubah
s = q.copy()
s[0] = 9
print(q) #tetep
print(s)

[5, 7]
[9, 7]


In [97]:
#jika kita ingin menambahakan jumlah semua elemen dalam array
a = np.array([5, 6, 7, 8]) #5 + 6 + 7 + 8 
a.sum()

26

In [98]:
#untuk menjumlahkan elemen dalam array sesuai baris dan kolom 
b = np.array([[4, 5, 7], [2, 3, 4]])
print(b)

[[4 5 7]
 [2 3 4]]


In [99]:
# sesuai baris dengan axis = 0
b.sum(axis=0)

array([ 6,  8, 11])

In [100]:
# sesuai baris dengan axis = 1
b.sum(axis=1)

array([16,  9])

In [107]:
#lalu kita dapat menggabungkan beberapa isi variabel dalam array (dengan operasi + - * /)
data = np.array([5, 6, 7])
data

array([5, 6, 7])

In [108]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [109]:
data + ones

array([6., 7., 8.])

In [110]:
#melakukan perkalian antara verktor dengan skalar atau array dengan dimensi yang berbeda
print(data)
print(data * 3)

[5 6 7]
[15 18 21]


In [112]:
#array operations seperti sum, min, max, mean, dsb
B = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(B)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [113]:
#sum
B.sum()

4.8595784

In [114]:
#min
B.min(axis=0) #nilai terkecil dari perkolom

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [116]:
#min
B.min(axis=1) #nilai terkecil dari perbaris

array([0.17296777, 0.05093587, 0.12697628])

In [115]:
#standar devisiasi
B.std()

0.21392120766089617

In [117]:
#memyimpan array kedalam file
B = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(B)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [120]:
np.save("exarrayhacktiv.npy",B)

In [119]:
responseFile = np.load('exarrayhacktiv.npy')
print(responseFile)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [121]:
#Latihan menyimpan file, melakukan load, dan mencari nilai min dan max pada file serta di setiap kolom dan baris
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(arr)

[[  0  72   3]
 [  1   3 -60]
 [ -3  -2   4]]


In [125]:
#menyimpan file
np.save("exarrayhacktiv2.npy",arr)

In [126]:
#men-load file
resfile = np.load('exarrayhacktiv2.npy')
print(resfile)

[[  0  72   3]
 [  1   3 -60]
 [ -3  -2   4]]


In [127]:
#mencetak nilai min dan max pada file, dan nilai min juga mx pada setiap kolom dan baris
print(resfile.min())
print(resfile.max())

print(repr(resfile.min(axis=0)))
print(repr(resfile.max(axis=0)))

print(repr(resfile.max(axis=-1)))
print(repr(resfile.min(axis=-1)))

-60
72
array([ -3,  -2, -60])
array([ 1, 72,  4])
array([72,  3,  4])
array([  0, -60,  -3])


Studi kasus
10 buah botol minum akan dibuat untuk menyimpan air dengan jari2 dan tinggi yang berbeda - beda . 
Besaran jari2 dan tinggi botol adalah bilang bulat kisaran 7 sampai dengan 20 cm . 

Temukan : 

1. Volume air yang dapat disimpan di setiap botol 
2. Total volume air yang tersimpan dalam semua botol 
3. Botol mana yang volume air terkecil dan temukan volumenya 
4. Botol mana yang menampung volume air terbesar dan temukan volume airnya . 
5. Rata-rata volume yang dapat di tampung di tiap botol 

In [128]:
#mencari volume air pada setiap botol
#1. melakukan generate tinggi dan jari" botol
import numpy as np 
np.random.seed(0)
dataBotol = np.random.randint(7,20,20)
print(dataBotol)

[19 12  7 10 18 10 14 16 10 12  9 11 14 13 15 15 19 17  8 13]


In [129]:
#2. mengenerate sebanyak 20
dataBotol.resize(10,2)
print(dataBotol)

[[19 12]
 [ 7 10]
 [18 10]
 [14 16]
 [10 12]
 [ 9 11]
 [14 13]
 [15 15]
 [19 17]
 [ 8 13]]


In [130]:
#3. menghitung volume
volume = np.pi * dataBotol[:,1]**2 * dataBotol[:,0]
print(volume)

[ 8595.39750022  2199.11485751  5654.86677646 11259.46807047
  4523.89342117  3421.19439976  7433.00821839 10602.87520587
 17250.48526086  4247.43326765]


In [131]:
#menghitung total volume
totalVolume = volume.sum()
print(f"Total volume  : {totalVolume} ")

Total volume  : 75187.73697836453 


In [132]:
#menentukan botol mana yang memiliki volum terkecil(min) dan berapa volumnya
volume.argmin() 
volume[volume.argmin()]

2199.1148575128555

In [133]:
#menentukan botol mana yang memiliki volum terkecil(max) dan berapa volumnya
volume.argmax()
volume[volume.argmax()]

17250.485260861555

In [135]:
#rata-rata volum air yang dapat ditampung di dalam botol terkecil dan terbesar
idxBotolKecil = volume.argmin()
volumeBotolKecil = volume[idxBotolKecil]
print(f"Botol Terkecil Pada Botol index : {idxBotolKecil} volume {volumeBotolKecil}")
idxBotolBesar = volume.argmax()
volumeBotolBesar = volume[idxBotolBesar]
print(f"Botol Terkecil Pada Botol index : {idxBotolBesar} volume {volumeBotolBesar}")


Botol Terkecil Pada Botol index : 1 volume 2199.1148575128555
Botol Terkecil Pada Botol index : 8 volume 17250.485260861555


Numpy read file csv

In [148]:
import csv

data = []

with open('world_population.csv') as csvfile:
    file_reader = csv.reader(csvfile, delimiter=',')
    for row in file_reader:
        data.append(row)
        
data = np.array(data) #convert the list of lists to a NumPy array

In [149]:
data.shape #melihat jumlah baris dan kolom

(235, 17)

In [150]:
data[3] #melihat data ke-3

array(['34', 'DZA', 'Algeria', 'Algiers', 'Africa', '44903225',
       '43451666', '39543154', '35856344', '30774621', '25518074',
       '18739378', '13795915', '2381741', '18.8531', '1.0164', '0.56'],
      dtype='<U32')

In [151]:
data.dtype.type

numpy.str_

In [152]:
np.save(open('data.npy', 'wb'), data) #menyimpan file data dengan .npy

In [153]:
newdata = np.load('data.npy')

In [154]:
newdata.shape

(235, 17)